[workspace]
name = "ccle-treatmentresponse-snakemake"
authors = ["Jermiah Joseph <bhklab.jermiahjoseph@gmail.com>"]
description = "Snakemake pipeline to curate and prepare the CCLE drug resonse data only."
license = "MIT"
channels = ["conda-forge", "bioconda"]
platforms = ["osx-64"] # "osx-arm64", "linux-64", "win-64",

[environments]
quality = { features = ["quality"], solve-group = "default" }
docs = { features = ["docs"], solve-group = "default" }
snakemake = ["snakemake", "R"]

[activation]
# convenient variables which can be used in scripts
env.CONFIG = "${PIXI_PROJECT_ROOT}/config"
env.METADATA = "${PIXI_PROJECT_ROOT}/metadata"
env.LOGS = "${PIXI_PROJECT_ROOT}/logs"
env.RAWDATA = "${PIXI_PROJECT_ROOT}/data/rawdata"
env.PROCDATA = "${PIXI_PROJECT_ROOT}/data/procdata"
env.RESULTS = "${PIXI_PROJECT_ROOT}/data/results"
env.SCRIPTS = "${PIXI_PROJECT_ROOT}/workflow/scripts"

[dependencies]
python = ">=3.12"
ipython = "*"
ipykernel = "*"
jupyterlab = "*"
pip = "*"

[pypi-dependencies]
damply = ">=0.10.0, <0.11"

[tasks]
example_script = { cmd = "python $SCRIPTS/example_script.py" }

[feature.snakemake.dependencies]
snakemake = "*"
snakemake-storage-plugin-http = "*"

[feature.R.dependencies]
r-base = "*"
r-essentials = "*"
"r-data.table" = "*"
r-devtools = ">=2.4.5,<3"
bioconductor-pharmacogx = ">=3.10.0,<4"
r-pak = ">=0.8.0.2,<0.9"

############################################## QUALITY ###############################################
# Quality includes linting, type checking, and formatting
[feature.quality.dependencies]
ruff = "*"

[feature.quality.tasks]
ruff-check.cmd = ["ruff", "check"]
ruff-check.inputs = ["config/ruff.toml", "workflow"]
ruff-check.description = "Run ruff check"
ruff-format.cmd = ["ruff", "format"]
ruff-format.inputs = ["config/ruff.toml", "workflow"]
ruff-format.depends-on = ["ruff-check"]
ruff-format.description = "Run ruff format, run check first"
qc.depends-on = ["ruff-format", "ruff-check"]
qc.description = "Quality check: ruff check and format"

############################################## DOCS ################################################
[feature.docs.dependencies]
mkdocs = "*"
mkdocs-include-markdown-plugin = ">=7.0.0,<8"

[feature.docs.tasks.doc-build]
cmd = "mkdocs build -f mkdocs.yaml"
inputs = ["docs"]
outputs = ["site"]
description = "Build documentation with mkdocs"

[feature.docs.tasks.doc-serve]
cmd = "mkdocs serve -f mkdocs.yaml"
depends-on = ["doc-build"]
inputs = ["docs"]
description = "Serve documentation with mkdocs, runs doc-build first"
