name: DATASET_NAME
description: TODO::(add description)

url: https://sites.broadinstitute.org/ccle/
# version: 2019

directories:
    rawdata: rawdata # Directory for raw data
    procdata: procdata # Directory for processed data
    metadata: metadata # Directory for metadata
    results: results # Directory for results
    logs: logs # Directory for logs

containers:
    annotationGx: "docker://bhklab/annotationgx-r:0.0.0.9097"

# Configure Data URLs
metadata:
    sampleAnnotation: https://data.broadinstitute.org/ccle/Cell_lines_annotations_20181226.txt
    treatmentAnnotation: https://data.broadinstitute.org/ccle_legacy_data/pharmacological_profiling/CCLE_NP24.2009_profiling_2012.02.20.csv
    # referenceGenome:
    #     description:
    #         Gene definitions (GENCODE19, GTEx7). URL is the file provided by the Broad Institute.
    #         However, gene annotation files used for molecularProfiles are downloaded from the GENCODE website.
    #     species: homo_sapiens
    #     release: 19
    #     build: GRCh37
    #     url: https://data.broadinstitute.org/ccle/gencode.v19.genes.v7_model.patched_contigs.gtf.gz

treatmentResponse:
    date: "2015-02-24"
    rawdata:
        description: "Dose response data"
        url: https://data.broadinstitute.org/ccle_legacy_data/pharmacological_profiling/CCLE_NP24.2009_Drug_data_2015.02.24.csv
    processed:
        description: "We did not include this data for now"
        url: https://data.broadinstitute.org/ccle_legacy_data/pharmacological_profiling/CCLE_GNF_data_090613.xls

# molecularProfiles:
#   rnaseq: # to name rnaseq
#     rsem-genes_tpm:
#       description: RNA-seq gene expression data. TPM values are log2 transformed.
#       url: https://data.broadinstitute.org/ccle/CCLE_RNAseq_rsem_genes_tpm_20180929.txt.gz
#     rsem-transcripts_tpm:
#       description: TODO::(add description)
#       url: https://data.broadinstitute.org/ccle/CCLE_RNAseq_rsem_transcripts_tpm_20180929.txt.gz
#     genes_counts:
#       description: TODO::(add description)
#       url: https://data.broadinstitute.org/ccle/CCLE_RNAseq_genes_counts_20180929.gct.gz
#     genes_rpkm:
#       description: TODO::(add description)
#       url: https://data.broadinstitute.org/ccle/CCLE_RNAseq_genes_rpkm_20180929.gct.gz

#   mutation:
#     oncomapAssay:
#       description: TODO::(add description)
#       tool: TODO::(add tool)
#       url: "https://data.broadinstitute.org/ccle_legacy_data/oncomap_mutations/CCLE_Oncomap3_Assays_2012-04-09.csv"
#     oncomap:
#       description: TODO::(add description)
#       tool: TODO::(add tool)
#       url: "https://data.broadinstitute.org/ccle_legacy_data/oncomap_mutations/CCLE_Oncomap3_2012-04-09.maf"
#     hybridCapture:
#       description: TODO::(add description)
#       tool: TODO::(add tool)
#       url: "https://data.broadinstitute.org/ccle_legacy_data/hybrid_capture_sequencing/CCLE_hybrid_capture1650_hg19_NoCommonSNPs_NoNeutralVariants_CDS_2012.05.07.maf"

#   cnv:
#     copynumber_byGene:
#       description: TODO::(add description)
#       tool: TODO::(add tool)
#       url: "https://data.broadinstitute.org/ccle_legacy_data/dna_copy_number/CCLE_copynumber_byGene_2013-12-03.txt.gz"
