name: Run Pipeline

on:
  push:
    branches:
      - main
      - "*"
    tags:
      - "v*.*"

permissions:
  contents: write

jobs:
  Run-Pipeline:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install Pixi
        uses: prefix-dev/setup-pixi@v0.8.8
        with:
          environments: "default"
          pixi-version: v0.47.0
          cache: true
          locked: true
          activate-environment: true
      - name: Run Snakemake
        run: |
          pixi run pipeline

      - name: Upload assets
        uses: actions/upload-artifact@v4
        with:
          name: CCLE-TreatmentResponseExperiment
          path: data/results/treatmentResponseExperiment.RDS